# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 01:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_type', models.CharField(choices=[('PT', 'Per term'), ('MO', 'Monthly'), ('WE', 'Weekly'), ('DA', 'Daily'), ('OT', 'One time')], default='OT', max_length=2)),
                ('sale_type', models.CharField(choices=[('SA', 'Sale'), ('RE', 'Rent')], default='SA', max_length=2)),
                ('description', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=100)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('image_dimensions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None), blank=True, null=True, size=None)),
                ('image_captions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('flags', models.PositiveIntegerField(default=0)),
                ('new', models.BooleanField(default=True)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(null=True)),
                ('closed', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('number_of_inquiries', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agora.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('text', models.TextField(max_length=2048, verbose_name='Text')),
                ('conversation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agora.Conversation', verbose_name='Conversation')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_listing', to='agora.Listing'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Read by'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(default=0, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
